### ISSUE TITLE
Can we bump gorm to latest version?

### ISSUE THREAD

**Issue by ghost** [Harry-027/go-notify#1]
I am looking at a lot of newly built go code using older versions even when the newer one is best practice and doesn't break but helps to improve the workflow. This is just my curiosity as a beginner and I felt like communicating with you straight up. Let me know your thoughts.

**Comment by Harry-027** [comment]
Newer one is best practice unless it has become a stable version. If you check the Gorm wiki, V2 is a complete rewrite from scratch & was released few months back. I don't see any vulnerability or performance issue with our old sweet Gorm version.
There could be many performance enhancements in V2 but still I don't see any strong reason to migrate to a newer version which is just few months old. Cheers!
